# version: "3.9"
# services:
#   backend:
#     build:
#       context: ./backend
#     ports:
#       - "8000:8000"
#     volumes:
#       - ./backend:/app
#     environment:
#       - PYTHONUNBUFFERED=1

#   frontend:
#     build:
#       context: ./frontend
#     ports:
#       - "5173:5173"
#     volumes:
#       - ./frontend:/app

version: "3.9"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
